### ISSUE TITLE
USER STORY: Spotify username on sign-up

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#10]
As a **user** I can **choose to add my Spotify username information when signing up to the application** so that **I don’t have to manually input this information later on**

## Acceptance Criteria:
1. Sign-up page shows field for Spotify username (made optional - for convenience)
2. Spotify username information is saved in database

## Tasks:
- [ ] Edit sign-up template html
- [ ] Save Spotify username in UserProfile.spotify_username object
- [ ] Form field must be optional - the option to add/update later in settings remains

**Comment by DestanT** [comment]
I may come back to this before the projects due date. Latest at a later stage of the applications life cycle.
