### ISSUE TITLE
USER STORY: Club Creation

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#11]
As a **user** I can **create isolated “clubs” and invite my friends** so that **I can have a set of functions that are unique to being in a club**

## Acceptance Criteria:
1. Users can create “Clubs” and name them
2. Club owners can invite friends to join their Club

## Tasks:
- [x] Club Model:
   - [x] club_name
   - [x] SlugField
   - [x] founder (ForeignKey)
   - [x] founded_on
   - [x] members (ManyToManyField - through MembersInClub model)
- [x] MembersInClubModel:
   - [x] date_joined
   - [x] member (ForeignKey)
   - [x] club_name (ForeignKey)
   - [x] Meta class: unique_together (members/club_name)
- [x] Created clubs are shown in the “Clubs” tab
- [ ] BooleanField for invite sent/accepted

**Comment by DestanT** [comment]
Will implement a form of "invite" feature in the next iteration of this user story
