### ISSUE TITLE
USER STORY: Finding other user profiles

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#14]
As a **user** I can **find the owner of the playlist I like** so that **I may see what other playlists that user may have posted**

## Acceptance Criteria:
1. Users can see the creator of the playlist
2. Users can click on the creator from the said playlist and view the user's profile

## Tasks:
- [x] In discover.html include links to the owner's profile in the playlist
- [x] Clicking on playlists sends users directly to "profile/<username>/playlist_<playlist_id>" link
- [x] Make profile pictures of users clickable - taking you directly to their profile playlists page

**Comment by DestanT** [comment]
Also included a search bar within discovery.html to better facilitate users finding each other
