### ISSUE TITLE
USER STORY: Accepting club invitations

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#19]
As a **user** I can **view club invitations** so that **I can accept them, and join the club of another user**

## Acceptance Criteria:
1. Club invites must be visible to the user
2. Club invites must be acceptable
3. Once accepted the user is a part of the club
4. The user can now view the club in their club view

## Tasks:
- [x] Display a notification to the user that they have a club invite
- [x] Users must be able to see who invited them
- [x] ..and to which club
- [x] Once accepted users can see this club in their club view
