### ISSUE TITLE
USER STORY: User Profile View

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#2]
As a **user** I can **view my profile** so that **I can see what groups I am a part of and what albums/playlists I’ve added**

## Acceptance Criteria:
1. Profile viewable by the user and other users
2. User can view **groups** they are a part of
3. User can see the albums/playlists they have added to their profile

## Tasks:
- [x] Create profile view
- [x] Create **groups** tab within the user profile
- [x] Create **albums** tab within the user profile
