### ISSUE TITLE
USER STORY: Viewing club details

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#20]
As a **user/club founder** I can **view the clubs I am a member of** so that **I can see some details about the club, such as other members**

## Acceptance Criteria:
1. Clubs must be clickable which opens the detail view on the club
2. Members can only view
3. Founders can also choose to edit the club to add more members

## Tasks:
- [x] club_detail.html template
- [x] Edit button for founders only
- [x] club_image visible
- [x] club_name visible
- [x] members in list format
