### ISSUE TITLE
USER STORY: Club Playlist Submissions

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#21]
As a **club member** I can **submit my playlists to the club I am a member of** so that **my submission can be seen by other fellow club members**

## Acceptance Criteria:
1. Be able submit playlists from user’s own profile to a club they are a member of
2. Other club members can see submitted albums 

## Tasks:
- [ ] Model to tie together a playlist with a club
   - [ ] Playlist should be protected from being deleted
- [ ] Display submitted playlists in club_details view
