### ISSUE TITLE
USER STORY: Club Seasons

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#22]
As a **club** we can **create seasons with their own themes** so that **our playlist submissions are based on the current theme and rated accordingly**

## Acceptance Criteria:
1. Themes are discussed and chosen via a message board within the Club view
2. One playlist submission per user per season
3. Submissions are sent to the club owner to approve and do final submission

## Tasks:
- [ ] Create a message board within Club view
- [ ] Limit submissions of playlists to one per user per season
- [ ] Submissions are sent to club owners for final approval and thereby submission (this is to simplify the process of checking theme validity through code)
