### ISSUE TITLE
USER STORY: Adding Playlists to Profile

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#3]
As a **user** I can **add playlists to my profile** so that **I can view and share them with friends**

## Acceptance Criteria:
1. User can add a playlist to their profile
2. Playlists can be named

## Tasks:
- [x] Create an “Add” button for users to click
- [x] Create a form for users to fill out
- [x] Save button to save the form data to the database
