### ISSUE TITLE
USER STORY: Profile and Background Picture Uploads

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#4]
As a **user** I can **upload my own profile and background pictures** so that **I can customise my profile**

## Acceptance Criteria:
1. Profile picture can be uploaded and is displayed on the profile of the user
2. Background picture can be uploaded and is displayed on the profile of the user

## Tasks:
- [x] Install and connect Cloudinary to the Django project
- [x] Update UserProfile model for profile image - Cloudinary Field
- [x] Update UserProfile model for background image - Cloudinary Field
- [x] Edit templates to reflect users' uploads
