### ISSUE TITLE
USER STORY: User’s Profile Settings Page

### ISSUE THREAD

**Issue by DestanT** [DestanT/we-rate-music#5]
As a **user** I can **view my profile’s settings** so that I can **upload my own profile and background picture**

## Acceptance Criteria:
1. Have user settings page
2. Be able to upload profile picture
3. Be able to upload background picture

## Tasks:
- [x] Create “Settings” template to view user’s profile settings
- [x] Connect views
- [x] URL Patterns - /settings
- [x] Create a form for profile and background picture uploads
